apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
data:
  GITHUB_PERSONAL_TOKEN: Z2hwX0dwNGt2UkZDcHVxQmprbnBadkN1S2kzenRCQlFhTDF4QW9wbgo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: aimvector/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: nehafathimaa
        - name: GITHUB_REPOSITORY
          value: docker-gh
        - name: GITHUB_PERSONAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_PERSONAL_TOKEN
